framework:
    messenger:
        default_bus: command.bus

        failure_transport: failed

        buses:
            command.bus: ~

            event.bus:
                default_middleware: allow_no_handlers

            query.bus: ~

        transports:
            main:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\Serializer\MessageSerializer
                options:
                    exchange:
                        name: main
                        type: direct
                        default_publish_routing_key: api
                    queues:
                        api:
                            binding_keys: [ api ]


            main_read:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\Serializer\MessageSerializer
                options:
                    exchange:
                        name: main
                        type: direct
                    queues:
                        school:
                            binding_keys: [ school ]

            failed: 'doctrine://default?queue_name=failed'


        routing:
            'App\Messenger\ArrayMessage': main
            'App\Messenger\TestArrayMessageIn': main_read
